mysql_master:
  host: "127.0.0.1"
  port: 3306
  user: ""
  password: ""
  database: "go_scheduler"
  max_idle: 10
  max_conn: 100

mysql_slaver:
  host: "127.0.0.1"
  port: 3306
  user: ""
  password: ""
  database: "go_scheduler"
  max_idle: 10
  max_conn: 100

redis_master:
  host: "127.0.0.1"
  port: 6380
  password: ""
  db: 0

redis_slaver:
  host: "127.0.0.1"
  port: 6380
  password: ""
  db: 0